# Task 2 — Data Profiling & Cleaning - stocks
## 1. Load Raw Data

In [1]:
import json
import pandas as pd
from pathlib import Path

In [2]:
raw_folder = Path("../data/raw")

In [3]:
# List the raw JSON files used for profiling and cleaning

raw_files = sorted(raw_folder.glob("tasilab_*_20260913.json"))

print(f"Number of raw files: {len(raw_files)}")

for file in raw_files:
    print(file.name)

Number of raw files: 15
tasilab_1120_20260913.json
tasilab_1211_20260913.json
tasilab_2010_20260913.json
tasilab_2080_20260913.json
tasilab_2280_20260913.json
tasilab_2310_20260913.json
tasilab_3030_20260913.json
tasilab_3060_20260913.json
tasilab_4003_20260913.json
tasilab_4030_20260913.json
tasilab_4190_20260913.json
tasilab_5110_20260913.json
tasilab_7010_20260913.json
tasilab_7020_20260913.json
tasilab_8210_20260913.json

In [4]:
with open(raw_files[0], "r", encoding="utf-8") as f:
    sample_data = json.load(f)

print(sample_data.keys())

dict_keys(['symbol', 'start', 'end', 'count', 'bars'])

In [5]:
print(sample_data["bars"][0])

{'symbol': '1120', 'date': '2013-01-01', 'open': '16.4380', 'high': '16.5630', 'low': '16.3130', 'close': '16.3755', 'adj_close': '10.5869', 'volume': 7578353}

In [6]:
df_sample = pd.DataFrame(sample_data["bars"])

df_sample.head()

  symbol        date     open     high      low    close adj_close    volume
0   1120  2013-01-01  16.4380  16.5630  16.3130  16.3755   10.5869   7578353
1   1120  2013-01-02  16.3755  16.7505  16.3755  16.6880   10.7890   9374450
2   1120  2013-01-03  61.6173  61.6173  61.6173  61.6173   39.8362         0
3   1120  2013-01-06  16.8755  16.8755  16.8130  16.8130   10.8698   4490083
4   1120  2013-01-07  16.8130  16.8755  16.6255  16.8755   10.9102  11432063

In [7]:
df_sample.shape

(3334, 8)

In [8]:
df_sample.dtypes

symbol         str
date           str
open           str
high           str
low            str
close          str
adj_close      str
volume       int64
dtype: object

In [9]:
df_sample.isnull().sum()

symbol       0
date         0
open         0
high         0
low          0
close        0
adj_close    0
volume       0
dtype: int64

In [10]:
df_sample.duplicated().sum()

np.int64(0)

In [11]:
df_sample.nunique()

symbol          1
date         3334
open         1239
high         1232
low          1286
close        1503
adj_close    1888
volume       3185
dtype: int64

In [12]:
df_sample.info()

<class 'pandas.DataFrame'>
RangeIndex: 3334 entries, 0 to 3333
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   symbol     3334 non-null   str
 1   date       3334 non-null   str
 2   open       3334 non-null   str
 3   high       3334 non-null   str
 4   low        3334 non-null   str
 5   close      3334 non-null   str
 6   adj_close  3334 non-null   str
 7   volume     3334 non-null   int64
dtypes: int64(1), str(7)
memory usage: 208.5 KB

In [13]:
profiling = []

for file in raw_files:
    with open(file, "r", encoding="utf-8") as f:
        data = json.load(f)

    df = pd.DataFrame(data["bars"])

    for column in df.columns:
        profiling.append({
            "file": file.name,
            "column": column,
            "dtype": str(df[column].dtype),
            "null_count": df[column].isnull().sum(),
            "null_pct": df[column].isnull().mean() * 100,
            "unique_count": df[column].nunique(),
            "sample_value": df[column].iloc[0]
        })

profiling_df = pd.DataFrame(profiling)

profiling_df

,file,column,dtype,null_count,null_pct,unique_count,sample_value
0,tasilab_1120_20260913.json,symbol,str,0,0.0,1,1120
1,tasilab_1120_20260913.json,date,str,0,0.0,3334,2013-01-01
2,tasilab_1120_20260913.json,open,str,0,0.0,1239,16.4380
3,tasilab_1120_20260913.json,high,str,0,0.0,1232,16.5630
4,tasilab_1120_20260913.json,low,str,0,0.0,1286,16.3130
...,...,...,...,...,...,...,...
115,tasilab_8210_20260913.json,high,str,0,0.0,1466,7.4400
116,tasilab_8210_20260913.json,low,str,0,0.0,1469,7.2000
117,tasilab_8210_20260913.json,close,str,0,0.0,1666,7.3067
118,tasilab_8210_20260913.json,adj_close,str,0,0.0,1978,5.9483
119,tasilab_8210_20260913.json,volume,int64,0,0.0,3151,1414406

In [14]:
for file in raw_files:
    with open(file, "r", encoding="utf-8") as f:
        data = json.load(f)

    df = pd.DataFrame(data["bars"])

    print(file.name, "duplicates:", df.duplicated().sum())

tasilab_1120_20260913.json duplicates: 0
tasilab_1211_20260913.json duplicates: 0
tasilab_2010_20260913.json duplicates: 0
tasilab_2080_20260913.json duplicates: 0
tasilab_2280_20260913.json duplicates: 0
tasilab_2310_20260913.json duplicates: 0
tasilab_3030_20260913.json duplicates: 0
tasilab_3060_20260913.json duplicates: 0
tasilab_4003_20260913.json duplicates: 0
tasilab_4030_20260913.json duplicates: 0
tasilab_4190_20260913.json duplicates: 0
tasilab_5110_20260913.json duplicates: 0
tasilab_7010_20260913.json duplicates: 0
tasilab_7020_20260913.json duplicates: 0
tasilab_8210_20260913.json duplicates: 0

## 3. Data Quality Issues
During profiling, the 15 stock datasets were checked for missing values and duplicate records. No missing values or duplicate rows were found.

The `date` column and the price columns (`open`, `high`, `low`, `close`, and `adj_close`) are stored as strings. These will be converted to the appropriate data types during cleaning.

Some records have a volume of 0. Since there is no clear indication that these values are invalid, they will be kept as they are.

## 4. Data Cleaning

In [15]:
price_columns = ["open", "high", "low", "close", "adj_close"]

cleaned_data = []

for file in raw_files:
    with open(file, "r", encoding="utf-8") as f:
        data = json.load(f)

    df = pd.DataFrame(data["bars"])

    # Convert date to datetime
    df["date"] = pd.to_datetime(df["date"])

    # Convert price columns to numeric
    for column in price_columns:
        df[column] = pd.to_numeric(df[column], errors="coerce")

    cleaned_data.append(df)

cleaned_df = pd.concat(cleaned_data, ignore_index=True)

cleaned_df.head()

  symbol       date     open     high      low    close  adj_close    volume
0   1120 2013-01-01  16.4380  16.5630  16.3130  16.3755    10.5869   7578353
1   1120 2013-01-02  16.3755  16.7505  16.3755  16.6880    10.7890   9374450
2   1120 2013-01-03  61.6173  61.6173  61.6173  61.6173    39.8362         0
3   1120 2013-01-06  16.8755  16.8755  16.8130  16.8130    10.8698   4490083
4   1120 2013-01-07  16.8130  16.8755  16.6255  16.8755    10.9102  11432063

In [16]:
cleaned_df.isnull().sum()

symbol       0
date         0
open         0
high         0
low          0
close        0
adj_close    0
volume       0
dtype: int64

In [17]:
cleaned_df.duplicated(subset=["symbol", "date"]).sum()

np.int64(0)

In [18]:
cleaned_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 49811 entries, 0 to 49810
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   symbol     49811 non-null  str
 1   date       49811 non-null  datetime64[us]
 2   open       49811 non-null  float64
 3   high       49811 non-null  float64
 4   low        49811 non-null  float64
 5   close      49811 non-null  float64
 6   adj_close  49811 non-null  float64
 7   volume     49811 non-null  int64
dtypes: datetime64[us](1), float64(5), int64(1), str(1)
memory usage: 3.0 MB

In [19]:
interim_folder = Path("../data/interim")
interim_folder.mkdir(parents=True, exist_ok=True)

cleaned_df.to_csv(
    interim_folder / "cleaned.csv",
    index=False
)

print("Saved:", interim_folder / "cleaned.csv")

Saved: ..\data\interim\cleaned.csv

In [20]:
print(cleaned_df.shape)
print(cleaned_df.head())

(49811, 8)
  symbol       date     open     high      low    close  adj_close    volume
0   1120 2013-01-01  16.4380  16.5630  16.3130  16.3755    10.5869   7578353
1   1120 2013-01-02  16.3755  16.7505  16.3755  16.6880    10.7890   9374450
2   1120 2013-01-03  61.6173  61.6173  61.6173  61.6173    39.8362         0
3   1120 2013-01-06  16.8755  16.8755  16.8130  16.8130    10.8698   4490083
4   1120 2013-01-07  16.8130  16.8755  16.6255  16.8755    10.9102  11432063