## TASK 2 — Data Profiling

The raw TASI dataset is profiled to understand its structure and data quality before applying any cleaning operations.

The profiling checks:

- Dataset dimensions
- Column names
- Data types
- Missing values
- Duplicate records
- Unique values
- Basic statistical information

This step helps identify potential data quality issues that need to be addressed during the cleaning stage.

In [2]:
# Step 1 — Load the RAW TASI dataset

import pandas as pd

raw_path = "../data/raw/tasi_raw.csv"

df = pd.read_csv(raw_path)

print("===== RAW DATA LOADED =====")
print("Shape:", df.shape)

display(df.head())

===== RAW DATA LOADED =====
Shape: (3174, 7)

          تاريخ   اخر سعر سعر الفتح      عالي     منخفض    الحجم التغير %
0  01‏/01‏/2014  8,605.34  8,535.60  8,605.56  8,535.22  184.63M    0.82%
1  02‏/01‏/2014  8,618.12  8,605.34  8,621.49  8,572.34  176.63M    0.15%
2  05‏/01‏/2014  8,637.74  8,618.12  8,638.25  8,602.35  184.30M    0.23%
3  06‏/01‏/2014  8,611.81  8,637.74  8,637.74  8,594.78  204.10M   -0.30%
4  07‏/01‏/2014  8,608.80  8,611.81  8,620.37  8,588.05  205.95M   -0.03%

In [4]:
# Step 2 — Profile the RAW TASI dataset

print("===== DATASET OVERVIEW =====")

print("\nShape:")
print(df.shape)

print("\nColumns:")
print(df.columns.tolist())

print("\nData Types:")
display(df.dtypes.to_frame("Data Type"))

print("\nMissing Values:")
display(df.isna().sum().to_frame("Missing Values"))

print("\nDuplicate Rows:")
print(df.duplicated().sum())

print("\nUnique Values per Column:")
display(df.nunique().to_frame("Unique Values"))

print("\nStatistical Summary:")
display(df.describe(include="all").T)

===== DATASET OVERVIEW =====

Shape:
(3174, 7)

Columns:
['تاريخ', 'اخر سعر', 'سعر الفتح', 'عالي', 'منخفض', 'الحجم', 'التغير %']

Data Types:

          Data Type
تاريخ           str
اخر سعر         str
سعر الفتح       str
عالي            str
منخفض           str
الحجم           str
التغير %        str

Missing Values:

           Missing Values
تاريخ                   0
اخر سعر                 0
سعر الفتح               0
عالي                    0
منخفض                   0
الحجم                   0
التغير %                0

Duplicate Rows:
0

Unique Values per Column:

           Unique Values
تاريخ               3174
اخر سعر             3169
سعر الفتح           3168
عالي                3161
منخفض               3168
الحجم               3020
التغير %             493

Statistical Summary:

          count unique           top freq
تاريخ      3174   3174  01‏/01‏/2014    1
اخر سعر    3174   3169      7,962.77    2
سعر الفتح  3174   3168     10,674.17    2
عالي       3174   3161      8,332.61    2
منخفض      3174   3168      6,935.87    2
الحجم      3174   3020       342.02M    3
التغير %   3174    493         0.12%   28

## Step 3 — Data Quality Checks

Based on the profiling results, the dataset is checked for common data quality issues before cleaning.

The following checks are performed:

- Missing values
- Duplicate records
- Date formatting issues
- Numeric values stored as text
- Unexpected characters in the source data
- Volume values containing unit suffixes such as M and B

These checks help define the cleaning rules that will be applied in the next step.

In [5]:
# Step 3 — Inspect data quality issues

print("===== DATA QUALITY CHECKS =====")

# Missing values
print("\nMissing Values:")
print(df.isna().sum().sum())

# Duplicate rows
print("\nDuplicate Rows:")
print(df.duplicated().sum())

# Data types
print("\nCurrent Data Types:")
display(df.dtypes.to_frame("Data Type"))

# Sample raw values
print("\nSample Raw Values:")
display(df.head(10))

===== DATA QUALITY CHECKS =====

Missing Values:
0

Duplicate Rows:
0

Current Data Types:

          Data Type
تاريخ           str
اخر سعر         str
سعر الفتح       str
عالي            str
منخفض           str
الحجم           str
التغير %        str

Sample Raw Values:

          تاريخ   اخر سعر سعر الفتح      عالي     منخفض    الحجم التغير %
0  01‏/01‏/2014  8,605.34  8,535.60  8,605.56  8,535.22  184.63M    0.82%
1  02‏/01‏/2014  8,618.12  8,605.34  8,621.49  8,572.34  176.63M    0.15%
2  05‏/01‏/2014  8,637.74  8,618.12  8,638.25  8,602.35  184.30M    0.23%
3  06‏/01‏/2014  8,611.81  8,637.74  8,637.74  8,594.78  204.10M   -0.30%
4  07‏/01‏/2014  8,608.80  8,611.81  8,620.37  8,588.05  205.95M   -0.03%
5  08‏/01‏/2014  8,652.50  8,608.79  8,659.26  8,604.03  234.83M    0.51%
6  09‏/01‏/2014  8,677.87  8,652.50  8,678.53  8,629.42  232.41M    0.29%
7  12‏/01‏/2014  8,714.73  8,677.87  8,714.73  8,649.91  231.85M    0.42%
8  13‏/01‏/2014  8,711.87  8,714.73  8,726.57  8,637.84  224.92M   -0.03%
9  14‏/01‏/2014  8,696.39  8,711.87  8,713.48  8,662.04  181.22M   -0.18%

## Step 4 — Standardize Column Names

The raw Arabic column names are renamed to clear English names to create a consistent dataset schema.

The standardized columns are:

- `Date`
- `Close`
- `Open`
- `High`
- `Low`
- `Volume`
- `Change%`

No values are modified in this step. Only the column names are standardized.

In [6]:
# Step 4 — Standardize column names

df.columns = [
    "Date",
    "Close",
    "Open",
    "High",
    "Low",
    "Volume",
    "Change%"
]

print("===== STANDARDIZED COLUMNS =====")
print(df.columns.tolist())

display(df.head())

===== STANDARDIZED COLUMNS =====
['Date', 'Close', 'Open', 'High', 'Low', 'Volume', 'Change%']

           Date     Close      Open      High       Low   Volume Change%
0  01‏/01‏/2014  8,605.34  8,535.60  8,605.56  8,535.22  184.63M   0.82%
1  02‏/01‏/2014  8,618.12  8,605.34  8,621.49  8,572.34  176.63M   0.15%
2  05‏/01‏/2014  8,637.74  8,618.12  8,638.25  8,602.35  184.30M   0.23%
3  06‏/01‏/2014  8,611.81  8,637.74  8,637.74  8,594.78  204.10M  -0.30%
4  07‏/01‏/2014  8,608.80  8,611.81  8,620.37  8,588.05  205.95M  -0.03%

## Step 5 — Clean and Convert Date

The `Date` column contains hidden right-to-left Unicode characters from the original source file.

These characters are removed before converting the column into a proper datetime format.

The expected source format is:

`DD/MM/YYYY`

The cleaned `Date` column will be stored as a datetime data type.

In [7]:
# Step 5 — Clean and convert the Date column

# Remove hidden right-to-left and left-to-right Unicode marks
df["Date"] = (
    df["Date"]
    .astype(str)
    .str.replace("\u200f", "", regex=False)
    .str.replace("\u200e", "", regex=False)
    .str.strip()
)

# Convert the cleaned values to datetime
df["Date"] = pd.to_datetime(
    df["Date"],
    format="%d/%m/%Y",
    errors="coerce"
)

print("===== DATE CLEANING =====")

print("Data Type:", df["Date"].dtype)
print("Missing Dates After Conversion:", df["Date"].isna().sum())

print("\nDate Range:")
print("First Date:", df["Date"].min())
print("Last Date:", df["Date"].max())

display(df[["Date"]].head())

===== DATE CLEANING =====
Data Type: datetime64[us]
Missing Dates After Conversion: 0

Date Range:
First Date: 2014-01-01 00:00:00
Last Date: 2026-09-20 00:00:00

        Date
0 2014-01-01
1 2014-01-02
2 2014-01-05
3 2014-01-06
4 2014-01-07

## Step 6 — Clean Price Columns

The `Close`, `Open`, `High`, and `Low` columns are originally stored as text because the source data contains comma separators.

The price columns are cleaned by:

- Removing comma separators.
- Converting the values from text to numeric data types.
- Checking for values that could not be converted.

This prepares the price fields for validation and downstream analysis.

In [8]:
# Step 6 — Clean and convert price columns

price_columns = ["Close", "Open", "High", "Low"]

for column in price_columns:
    # Remove comma separators and convert to numeric
    df[column] = (
        df[column]
        .astype(str)
        .str.replace(",", "", regex=False)
        .str.strip()
    )
    
    df[column] = pd.to_numeric(df[column], errors="coerce")

print("===== PRICE CLEANING =====")

print("\nData Types:")
display(df[price_columns].dtypes.to_frame("Data Type"))

print("\nMissing Values After Conversion:")
display(df[price_columns].isna().sum().to_frame("Missing Values"))

print("\nSample Cleaned Prices:")
display(df[price_columns].head())

===== PRICE CLEANING =====

Data Types:

      Data Type
Close   float64
Open    float64
High    float64
Low     float64

Missing Values After Conversion:

       Missing Values
Close               0
Open                0
High                0
Low                 0

Sample Cleaned Prices:

     Close     Open     High      Low
0  8605.34  8535.60  8605.56  8535.22
1  8618.12  8605.34  8621.49  8572.34
2  8637.74  8618.12  8638.25  8602.35
3  8611.81  8637.74  8637.74  8594.78
4  8608.80  8611.81  8620.37  8588.05

## Step 7 — Clean and Convert Volume

The `Volume` column contains numeric values followed by unit suffixes such as:

- `K` for thousands
- `M` for millions
- `B` for billions

The suffixes are converted into their corresponding numeric multipliers so that the entire column can be stored as a numeric value.

For example:

- `184.63M` → `184,630,000`
- `1.2B` → `1,200,000,000`

The cleaned `Volume` column will be stored as a numeric data type.

In [9]:
# Step 7 — Clean and convert the Volume column

def convert_volume(value):
    value = str(value).strip().replace(",", "")
    
    if value.endswith("B"):
        return float(value[:-1]) * 1_000_000_000
    elif value.endswith("M"):
        return float(value[:-1]) * 1_000_000
    elif value.endswith("K"):
        return float(value[:-1]) * 1_000
    else:
        return pd.to_numeric(value, errors="coerce")


df["Volume"] = df["Volume"].apply(convert_volume)

print("===== VOLUME CLEANING =====")

print("\nData Type:")
print(df["Volume"].dtype)

print("\nMissing Values After Conversion:")
print(df["Volume"].isna().sum())

print("\nSample Cleaned Volume:")
display(df[["Volume"]].head())

===== VOLUME CLEANING =====

Data Type:
float64

Missing Values After Conversion:
0

Sample Cleaned Volume:

        Volume
0  184630000.0
1  176630000.0
2  184300000.0
3  204100000.0
4  205950000.0

## Step 8 — Clean and Convert Change%

The `Change%` column contains percentage values stored as text with a `%` symbol.

The percentage symbol is removed and the values are converted into a numeric data type.

The resulting values represent the daily percentage change as numeric values.

In [10]:
# Step 8 — Clean and convert the Change% column

df["Change%"] = (
    df["Change%"]
    .astype(str)
    .str.replace("%", "", regex=False)
    .str.replace(",", "", regex=False)
    .str.strip()
)

df["Change%"] = pd.to_numeric(
    df["Change%"],
    errors="coerce"
)

print("===== CHANGE% CLEANING =====")

print("\nData Type:")
print(df["Change%"].dtype)

print("\nMissing Values After Conversion:")
print(df["Change%"].isna().sum())

print("\nSample Cleaned Change%:")
display(df[["Change%"]].head())

===== CHANGE% CLEANING =====

Data Type:
float64

Missing Values After Conversion:
0

Sample Cleaned Change%:

   Change%
0     0.82
1     0.15
2     0.23
3    -0.30
4    -0.03

## Step 9 — Save Cleaned Dataset

The cleaned TASI dataset is saved to the PROCESSED layer.

The RAW dataset remains unchanged, while the cleaned version is stored separately for downstream schema validation and integration.

Output:

`../data/processed/tasi_cleaned.csv`

In [13]:
# Step 9 — Save the cleaned TASI dataset

from pathlib import Path

processed_folder = Path("../data/processed")
processed_folder.mkdir(parents=True, exist_ok=True)

processed_path = processed_folder / "tasi_cleaned.csv"

df.to_csv(processed_path, index=False)

print("===== CLEANED DATA SAVED =====")
print("Output file:", processed_path.resolve())
print("Rows:", len(df))
print("Columns:", len(df.columns))
print("Status: Cleaned dataset saved successfully.")

===== CLEANED DATA SAVED =====
Output file: C:\Users\aldos\Saudi_FinHub_Project\data\processed\tasi_cleaned.csv
Rows: 3174
Columns: 7
Status: Cleaned dataset saved successfully.